![JohnSnowLabs](https://nlp.johnsnowlabs.com/assets/images/logo.png)

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/JohnSnowLabs/spark-nlp-workshop/blob/master/tutorials/PySpark/3.PySpark_Read_File_into_DataFrame.ipynb)

# **PySpark Tutorial-3 Read File into DataFrame**

## **Overview**

In this notebook, load and save operations of data files supported by PySpark are performed.

There are many other data sources available in PySpark such as csv, json, parquet, JDBC, text, binaryFile, Avro, etc. See also the latest [Spark SQL, DataFrames and Datasets Guide](https://spark.apache.org/docs/latest/sql-programming-guide.html) in Apache Spark documentation.

[source](https://spark.apache.org/docs/latest/sql-getting-started.html)

### **Install PySpark**

In [ ]:
# install PySpark
! pip install pyspark==3.2.0

### **Initializing Spark**

In [ ]:
from pyspark.sql import SparkSession

spark = SparkSession.builder.getOrCreate()

spark

**Import Libraries**

In [ ]:
import pandas as pd

## **Download All Dataset**

In [ ]:
! wget -q https://raw.githubusercontent.com/JohnSnowLabs/spark-nlp-workshop/master/tutorials/PySpark/data/airport-codes.csv
! wget -q https://raw.githubusercontent.com/JohnSnowLabs/spark-nlp-workshop/master/tutorials/PySpark/data/Amazon_Food.parquet
! wget -q https://raw.githubusercontent.com/JohnSnowLabs/spark-nlp-workshop/master/tutorials/PySpark/data/car_crashes.json
! wget -q https://raw.githubusercontent.com/JohnSnowLabs/spark-nlp-workshop/master/tutorials/PySpark/data/sherlockholmes.txt
! wget -q https://raw.githubusercontent.com/JohnSnowLabs/spark-nlp-workshop/master/tutorials/PySpark/data/taxis.csv
! wget -q https://raw.githubusercontent.com/JohnSnowLabs/spark-nlp-workshop/master/tutorials/PySpark/data/taxis.tsv
! wget -q https://raw.githubusercontent.com/JohnSnowLabs/spark-nlp-workshop/master/tutorials/PySpark/data/taxis_tab.csv

### **CSV Files**
Spark SQL provides **spark.read().csv("file_name")** to read a file or directory of files in CSV format into Spark DataFrame, and **dataframe.write().csv("path")** to write to a CSV file. Function **option()** can be used to customize the behavior of reading or writing, such as controlling behavior of the header, delimiter character, character set, and so on.

In [ ]:
# Write and Read CSV files

# df.write.csv('file_name.csv', header=True)
# df = spark.read.csv('file_name.csv', header=True)

**delimiter = " , "**

In [ ]:
csv_path = "/content/taxis.csv"

In [ ]:
taxis = spark.read.csv(csv_path,header=True)

In [ ]:
taxis.show(10)

+-------------------+-------------------+----------+--------+----+----+-----+-----+------+-----------+--------------------+--------------------+--------------+---------------+
|             pickup|            dropoff|passengers|distance|fare| tip|tolls|total| color|    payment|         pickup_zone|        dropoff_zone|pickup_borough|dropoff_borough|
+-------------------+-------------------+----------+--------+----+----+-----+-----+------+-----------+--------------------+--------------------+--------------+---------------+
|2019-03-23 20:21:09|2019-03-23 20:27:24|         1|     1.6| 7.0|2.15|  0.0|12.95|yellow|credit card|     Lenox Hill West| UN/Turtle Bay South|     Manhattan|      Manhattan|
|2019-03-04 16:11:55|2019-03-04 16:19:00|         1|    0.79| 5.0| 0.0|  0.0|  9.3|yellow|       cash|Upper West Side S...|Upper West Side S...|     Manhattan|      Manhattan|
|2019-03-27 17:53:01|2019-03-27 18:00:25|         1|    1.37| 7.5|2.36|  0.0|14.16|yellow|credit card|       Alphabet City|        West Village|     Manhattan|      Manhattan|
|2019-03-10 01:23:59|2019-03-10 01:49:51|         1|     7.7|27.0|6.15|  0.0|36.95|yellow|credit card|           Hudson Sq|      Yorkville West|     Manhattan|      Manhattan|
|2019-03-30 13:27:42|2019-03-30 13:37:14|         3|    2.16| 9.0| 1.1|  0.0| 13.4|yellow|credit card|        Midtown East|      Yorkville West|     Manhattan|      Manhattan|
|2019-03-11 10:37:23|2019-03-11 10:47:31|         1|    0.49| 7.5|2.16|  0.0|12.96|yellow|credit card|Times Sq/Theatre ...|        Midtown East|     Manhattan|      Manhattan|
|2019-03-26 21:07:31|2019-03-26 21:17:29|         1|    3.65|13.0| 2.0|  0.0| 18.8|yellow|credit card|   Battery Park City|Two Bridges/Sewar...|     Manhattan|      Manhattan|
|2019-03-22 12:47:13|2019-03-22 12:58:17|         0|     1.4| 8.5| 0.0|  0.0| 11.8|yellow|       null|         Murray Hill|            Flatiron|     Manhattan|      Manhattan|
|2019-03-23 11:48:50|2019-03-23 12:06:14|         1|    3.63|15.0| 1.0|  0.0| 19.3|yellow|credit card|   East Harlem South|      Midtown Center|     Manhattan|      Manhattan|
|2019-03-08 16:18:37|2019-03-08 16:26:57|         1|    1.52| 8.0| 1.0|  0.0| 13.3|yellow|credit card| Lincoln Square East|        Central Park|     Manhattan|      Manhattan|
+-------------------+-------------------+----------+--------+----+----+-----+-----+------+-----------+--------------------+--------------------+--------------+---------------+
only showing top 10 rows

In [ ]:
taxis2 = spark.read.options(delimiter=",", header=True).csv(csv_path)

In [ ]:
taxis2.show(10)

+-------------------+-------------------+----------+--------+----+----+-----+-----+------+-----------+--------------------+--------------------+--------------+---------------+
|             pickup|            dropoff|passengers|distance|fare| tip|tolls|total| color|    payment|         pickup_zone|        dropoff_zone|pickup_borough|dropoff_borough|
+-------------------+-------------------+----------+--------+----+----+-----+-----+------+-----------+--------------------+--------------------+--------------+---------------+
|2019-03-23 20:21:09|2019-03-23 20:27:24|         1|     1.6| 7.0|2.15|  0.0|12.95|yellow|credit card|     Lenox Hill West| UN/Turtle Bay South|     Manhattan|      Manhattan|
|2019-03-04 16:11:55|2019-03-04 16:19:00|         1|    0.79| 5.0| 0.0|  0.0|  9.3|yellow|       cash|Upper West Side S...|Upper West Side S...|     Manhattan|      Manhattan|
|2019-03-27 17:53:01|2019-03-27 18:00:25|         1|    1.37| 7.5|2.36|  0.0|14.16|yellow|credit card|       Alphabet City|        West Village|     Manhattan|      Manhattan|
|2019-03-10 01:23:59|2019-03-10 01:49:51|         1|     7.7|27.0|6.15|  0.0|36.95|yellow|credit card|           Hudson Sq|      Yorkville West|     Manhattan|      Manhattan|
|2019-03-30 13:27:42|2019-03-30 13:37:14|         3|    2.16| 9.0| 1.1|  0.0| 13.4|yellow|credit card|        Midtown East|      Yorkville West|     Manhattan|      Manhattan|
|2019-03-11 10:37:23|2019-03-11 10:47:31|         1|    0.49| 7.5|2.16|  0.0|12.96|yellow|credit card|Times Sq/Theatre ...|        Midtown East|     Manhattan|      Manhattan|
|2019-03-26 21:07:31|2019-03-26 21:17:29|         1|    3.65|13.0| 2.0|  0.0| 18.8|yellow|credit card|   Battery Park City|Two Bridges/Sewar...|     Manhattan|      Manhattan|
|2019-03-22 12:47:13|2019-03-22 12:58:17|         0|     1.4| 8.5| 0.0|  0.0| 11.8|yellow|       null|         Murray Hill|            Flatiron|     Manhattan|      Manhattan|
|2019-03-23 11:48:50|2019-03-23 12:06:14|         1|    3.63|15.0| 1.0|  0.0| 19.3|yellow|credit card|   East Harlem South|      Midtown Center|     Manhattan|      Manhattan|
|2019-03-08 16:18:37|2019-03-08 16:26:57|         1|    1.52| 8.0| 1.0|  0.0| 13.3|yellow|credit card| Lincoln Square East|        Central Park|     Manhattan|      Manhattan|
+-------------------+-------------------+----------+--------+----+----+-----+-----+------+-----------+--------------------+--------------------+--------------+---------------+
only showing top 10 rows

**delimiter = " \t "**

In [ ]:
csv_path = "/content/taxis_tab.csv"

In [ ]:
data_taxis = spark.read.options(delimiter="\t",header=True).csv(csv_path)

In [ ]:
data_taxis.show(10)

+-----+-------------------+-------------------+----------+--------+----+----+-----+-----+------+-----------+--------------------+--------------------+--------------+---------------+
|index|             pickup|            dropoff|passengers|distance|fare| tip|tolls|total| color|    payment|         pickup_zone|        dropoff_zone|pickup_borough|dropoff_borough|
+-----+-------------------+-------------------+----------+--------+----+----+-----+-----+------+-----------+--------------------+--------------------+--------------+---------------+
|    0|2019-03-23 20:21:09|2019-03-23 20:27:24|         1|     1.6| 7.0|2.15|  0.0|12.95|yellow|credit card|     Lenox Hill West| UN/Turtle Bay South|     Manhattan|      Manhattan|
|    1|2019-03-04 16:11:55|2019-03-04 16:19:00|         1|    0.79| 5.0| 0.0|  0.0|  9.3|yellow|       cash|Upper West Side S...|Upper West Side S...|     Manhattan|      Manhattan|
|    2|2019-03-27 17:53:01|2019-03-27 18:00:25|         1|    1.37| 7.5|2.36|  0.0|14.16|yellow|credit card|       Alphabet City|        West Village|     Manhattan|      Manhattan|
|    3|2019-03-10 01:23:59|2019-03-10 01:49:51|         1|     7.7|27.0|6.15|  0.0|36.95|yellow|credit card|           Hudson Sq|      Yorkville West|     Manhattan|      Manhattan|
|    4|2019-03-30 13:27:42|2019-03-30 13:37:14|         3|    2.16| 9.0| 1.1|  0.0| 13.4|yellow|credit card|        Midtown East|      Yorkville West|     Manhattan|      Manhattan|
|    5|2019-03-11 10:37:23|2019-03-11 10:47:31|         1|    0.49| 7.5|2.16|  0.0|12.96|yellow|credit card|Times Sq/Theatre ...|        Midtown East|     Manhattan|      Manhattan|
|    6|2019-03-26 21:07:31|2019-03-26 21:17:29|         1|    3.65|13.0| 2.0|  0.0| 18.8|yellow|credit card|   Battery Park City|Two Bridges/Sewar...|     Manhattan|      Manhattan|
|    7|2019-03-22 12:47:13|2019-03-22 12:58:17|         0|     1.4| 8.5| 0.0|  0.0| 11.8|yellow|       null|         Murray Hill|            Flatiron|     Manhattan|      Manhattan|
|    8|2019-03-23 11:48:50|2019-03-23 12:06:14|         1|    3.63|15.0| 1.0|  0.0| 19.3|yellow|credit card|   East Harlem South|      Midtown Center|     Manhattan|      Manhattan|
|    9|2019-03-08 16:18:37|2019-03-08 16:26:57|         1|    1.52| 8.0| 1.0|  0.0| 13.3|yellow|credit card| Lincoln Square East|        Central Park|     Manhattan|      Manhattan|
+-----+-------------------+-------------------+----------+--------+----+----+-----+-----+------+-----------+--------------------+--------------------+--------------+---------------+
only showing top 10 rows

**TSV files  (Tab-separated Values )**

In [ ]:
tsv_path = "/content/taxis.tsv"

data_taxiss = spark.read.options(delimiter="\t",header=True).csv(tsv_path)

data_taxiss.show(10)

+-----+-------------------+-------------------+----------+--------+----+----+-----+-----+------+-----------+--------------------+--------------------+--------------+---------------+
|index|             pickup|            dropoff|passengers|distance|fare| tip|tolls|total| color|    payment|         pickup_zone|        dropoff_zone|pickup_borough|dropoff_borough|
+-----+-------------------+-------------------+----------+--------+----+----+-----+-----+------+-----------+--------------------+--------------------+--------------+---------------+
|    0|2019-03-23 20:21:09|2019-03-23 20:27:24|         1|     1.6| 7.0|2.15|  0.0|12.95|yellow|credit card|     Lenox Hill West| UN/Turtle Bay South|     Manhattan|      Manhattan|
|    1|2019-03-04 16:11:55|2019-03-04 16:19:00|         1|    0.79| 5.0| 0.0|  0.0|  9.3|yellow|       cash|Upper West Side S...|Upper West Side S...|     Manhattan|      Manhattan|
|    2|2019-03-27 17:53:01|2019-03-27 18:00:25|         1|    1.37| 7.5|2.36|  0.0|14.16|yellow|credit card|       Alphabet City|        West Village|     Manhattan|      Manhattan|
|    3|2019-03-10 01:23:59|2019-03-10 01:49:51|         1|     7.7|27.0|6.15|  0.0|36.95|yellow|credit card|           Hudson Sq|      Yorkville West|     Manhattan|      Manhattan|
|    4|2019-03-30 13:27:42|2019-03-30 13:37:14|         3|    2.16| 9.0| 1.1|  0.0| 13.4|yellow|credit card|        Midtown East|      Yorkville West|     Manhattan|      Manhattan|
|    5|2019-03-11 10:37:23|2019-03-11 10:47:31|         1|    0.49| 7.5|2.16|  0.0|12.96|yellow|credit card|Times Sq/Theatre ...|        Midtown East|     Manhattan|      Manhattan|
|    6|2019-03-26 21:07:31|2019-03-26 21:17:29|         1|    3.65|13.0| 2.0|  0.0| 18.8|yellow|credit card|   Battery Park City|Two Bridges/Sewar...|     Manhattan|      Manhattan|
|    7|2019-03-22 12:47:13|2019-03-22 12:58:17|         0|     1.4| 8.5| 0.0|  0.0| 11.8|yellow|       null|         Murray Hill|            Flatiron|     Manhattan|      Manhattan|
|    8|2019-03-23 11:48:50|2019-03-23 12:06:14|         1|    3.63|15.0| 1.0|  0.0| 19.3|yellow|credit card|   East Harlem South|      Midtown Center|     Manhattan|      Manhattan|
|    9|2019-03-08 16:18:37|2019-03-08 16:26:57|         1|    1.52| 8.0| 1.0|  0.0| 13.3|yellow|credit card| Lincoln Square East|        Central Park|     Manhattan|      Manhattan|
+-----+-------------------+-------------------+----------+--------+----+----+-----+-----+------+-----------+--------------------+--------------------+--------------+---------------+
only showing top 10 rows

**.format().options().load()**

In [ ]:
df = spark.read.format("csv").options(delimiter=",", header=True).load("/content/taxis.csv")
df.show(10)

+-------------------+-------------------+----------+--------+----+----+-----+-----+------+-----------+--------------------+--------------------+--------------+---------------+
|             pickup|            dropoff|passengers|distance|fare| tip|tolls|total| color|    payment|         pickup_zone|        dropoff_zone|pickup_borough|dropoff_borough|
+-------------------+-------------------+----------+--------+----+----+-----+-----+------+-----------+--------------------+--------------------+--------------+---------------+
|2019-03-23 20:21:09|2019-03-23 20:27:24|         1|     1.6| 7.0|2.15|  0.0|12.95|yellow|credit card|     Lenox Hill West| UN/Turtle Bay South|     Manhattan|      Manhattan|
|2019-03-04 16:11:55|2019-03-04 16:19:00|         1|    0.79| 5.0| 0.0|  0.0|  9.3|yellow|       cash|Upper West Side S...|Upper West Side S...|     Manhattan|      Manhattan|
|2019-03-27 17:53:01|2019-03-27 18:00:25|         1|    1.37| 7.5|2.36|  0.0|14.16|yellow|credit card|       Alphabet City|        West Village|     Manhattan|      Manhattan|
|2019-03-10 01:23:59|2019-03-10 01:49:51|         1|     7.7|27.0|6.15|  0.0|36.95|yellow|credit card|           Hudson Sq|      Yorkville West|     Manhattan|      Manhattan|
|2019-03-30 13:27:42|2019-03-30 13:37:14|         3|    2.16| 9.0| 1.1|  0.0| 13.4|yellow|credit card|        Midtown East|      Yorkville West|     Manhattan|      Manhattan|
|2019-03-11 10:37:23|2019-03-11 10:47:31|         1|    0.49| 7.5|2.16|  0.0|12.96|yellow|credit card|Times Sq/Theatre ...|        Midtown East|     Manhattan|      Manhattan|
|2019-03-26 21:07:31|2019-03-26 21:17:29|         1|    3.65|13.0| 2.0|  0.0| 18.8|yellow|credit card|   Battery Park City|Two Bridges/Sewar...|     Manhattan|      Manhattan|
|2019-03-22 12:47:13|2019-03-22 12:58:17|         0|     1.4| 8.5| 0.0|  0.0| 11.8|yellow|       null|         Murray Hill|            Flatiron|     Manhattan|      Manhattan|
|2019-03-23 11:48:50|2019-03-23 12:06:14|         1|    3.63|15.0| 1.0|  0.0| 19.3|yellow|credit card|   East Harlem South|      Midtown Center|     Manhattan|      Manhattan|
|2019-03-08 16:18:37|2019-03-08 16:26:57|         1|    1.52| 8.0| 1.0|  0.0| 13.3|yellow|credit card| Lincoln Square East|        Central Park|     Manhattan|      Manhattan|
+-------------------+-------------------+----------+--------+----+----+-----+-----+------+-----------+--------------------+--------------------+--------------+---------------+
only showing top 10 rows

## **JSON Files**

Spark SQL can automatically infer the schema of a JSON dataset and load it as a DataFrame. This conversion can be done using SparkSession.read.json on a JSON file.

Note that the file that is offered as a json file is not a typical JSON file. Each line must contain a separate, self-contained valid JSON object.

In [ ]:
# Write and Read json file

# df.write.json('file_name.json')
# df = spark.read.json('file_name.json')

In [ ]:
json_path = "/content/car_crashes.json"

car = spark.read.json(json_path)

car.show(10)

+------+-------+----------+-----------+-----------+--------------+--------+-----+
|abbrev|alcohol|ins_losses|ins_premium|no_previous|not_distracted|speeding|total|
+------+-------+----------+-----------+-----------+--------------+--------+-----+
|    AL|   5.64|    145.08|     784.55|      15.04|        18.048|   7.332| 18.8|
|    AK|  4.525|    133.93|    1053.48|     17.014|         16.29|   7.421| 18.1|
|    AZ|  5.208|    110.35|     899.47|     17.856|        15.624|    6.51| 18.6|
|    AR|  5.824|    142.39|     827.34|      21.28|        21.056|   4.032| 22.4|
|    CA|   3.36|    165.63|     878.41|      10.68|         10.92|     4.2| 12.0|
|    CO|  3.808|    139.91|      835.5|      12.92|        10.744|   5.032| 13.6|
|    CT|  3.888|    167.02|    1068.73|      8.856|         9.396|   4.968| 10.8|
|    DE|   4.86|    151.48|    1137.87|     16.038|        14.094|   6.156| 16.2|
|    DC|  1.593|    136.05|    1273.89|        5.9|           5.9|   2.006|  5.9|
|    FL|  5.191|    144.18|    1160.13|     16.826|        16.468|   3.759| 17.9|
+------+-------+----------+-----------+-----------+--------------+--------+-----+
only showing top 10 rows

## **Parquet Files**
Parquet is a columnar format that is supported by many other data processing systems. Spark SQL provides support for both reading and writing Parquet files that automatically preserves the schema of the original data. When reading Parquet files, all columns are automatically converted to be nullable for compatibility reasons.

In [ ]:
# Write and Read PARQUET

# df.write.parquet('file_name.parquet')
# df = spark.read.parquet('file_name.parquet')

In [ ]:
parquetFile = spark.read.parquet("amazonFood.parquet")

parquetFile.show(10)

+----------+--------------+--------------------+-----+--------------------+--------------------+
| ProductId|        UserId|         productName|Score|             Summary|                Text|
+----------+--------------+--------------------+-----+--------------------+--------------------+
|B001E4KFG0|A3SGXH7AUHU8GW|Dogswell Vitality...|    5|Good Quality Dog ...|I have bought sev...|
|B00813GRG4|A1D87F6ZCVE5NK|Southern Grove Pr...|    1|   Not as Advertised|Product arrived l...|
|B000LQOCH0| ABXLMWJIXXAIN|Turkish Delight F...|    4|"Delight" says it...|This is a confect...|
|B000UA0QIQ|A395BORC6FGVXV|Faeries Finest Fl...|    2|      Cough Medicine|If you are lookin...|
|B006K2ZZ7K|A1UQRSCLF8GW1T|Salt Water Taffy ...|    5|         Great taffy|Great taffy at a ...|
|B006K2ZZ7K| ADT0SRK1MGOEU|Salt Water Taffy ...|    4|          Nice Taffy|I got a wild hair...|
|B006K2ZZ7K|A1SP2KVKFXXRU1|Salt Water Taffy ...|    5|Great!  Just as g...|This saltwater ta...|
|B006K2ZZ7K|A3JRGQVEQN31IQ|Salt Water Taffy ...|    5|Wonderful, tasty ...|This taffy is so ...|
|B000E7L2R4|A1MZYO9TZK0BBI|Organic Barley Se...|    5|          Yay Barley|Right now I'm mos...|
|B00171APVA|A21BT40VZCCYT4|Eukanuba Natural ...|    5|    Healthy Dog Food|This is a very he...|
+----------+--------------+--------------------+-----+--------------------+--------------------+
only showing top 10 rows

In [ ]:
parquetFile = spark.read.option("delimiter", ";")\
                        .option("header", True)\
                        .parquet("amazonFood.parquet")
                        
parquetFile.show(10)

+----------+--------------+--------------------+-----+--------------------+--------------------+
| ProductId|        UserId|         productName|Score|             Summary|                Text|
+----------+--------------+--------------------+-----+--------------------+--------------------+
|B001E4KFG0|A3SGXH7AUHU8GW|Dogswell Vitality...|    5|Good Quality Dog ...|I have bought sev...|
|B00813GRG4|A1D87F6ZCVE5NK|Southern Grove Pr...|    1|   Not as Advertised|Product arrived l...|
|B000LQOCH0| ABXLMWJIXXAIN|Turkish Delight F...|    4|"Delight" says it...|This is a confect...|
|B000UA0QIQ|A395BORC6FGVXV|Faeries Finest Fl...|    2|      Cough Medicine|If you are lookin...|
|B006K2ZZ7K|A1UQRSCLF8GW1T|Salt Water Taffy ...|    5|         Great taffy|Great taffy at a ...|
|B006K2ZZ7K| ADT0SRK1MGOEU|Salt Water Taffy ...|    4|          Nice Taffy|I got a wild hair...|
|B006K2ZZ7K|A1SP2KVKFXXRU1|Salt Water Taffy ...|    5|Great!  Just as g...|This saltwater ta...|
|B006K2ZZ7K|A3JRGQVEQN31IQ|Salt Water Taffy ...|    5|Wonderful, tasty ...|This taffy is so ...|
|B000E7L2R4|A1MZYO9TZK0BBI|Organic Barley Se...|    5|          Yay Barley|Right now I'm mos...|
|B00171APVA|A21BT40VZCCYT4|Eukanuba Natural ...|    5|    Healthy Dog Food|This is a very he...|
+----------+--------------+--------------------+-----+--------------------+--------------------+
only showing top 10 rows

## **Text Files**
Spark SQL provides **spark.read().text("file_name")** to read a file or directory of text files into a Spark DataFrame, and **dataframe.write().text("path")** to write to a text file. When reading a text file, each line becomes each row that has string “value” column by default. The line separator can be changed as shown in the example below. The **option()** function can be used to customize the behavior of reading or writing, such as controlling behavior of the line separator, compression, and so on.

In [ ]:
# Write and Read Text files

# df.write().text("file_name.txt")
# df = spark.read().text("file_name.txt")

In [ ]:
txt_path = "/content/sherlockholmes.txt"

sherlock_txt = spark.read.text(txt_path)

sherlock_txt.show(truncate=False)

+------------------------------------------------------------------------+
|value                                                                   |
+------------------------------------------------------------------------+
|  THE COMPLETE SHERLOCK HOLMES - Arthur Conan Doyle                     |
|                                                                        |
|       A STUDY IN SCARLET                                               |
|                                                                        |
|                         PART I                                         |
|                                                                        |
|       (Being a reprint from the reminiscences of                       |
|                   John H. Watson, M.D.,                                |
|          late of the Army Medical Department.)                         |
|                                                                        |
|                                                                        |
|          CHAPTER I                                                     |
|          Mr. Sherlock Holmes                                           |
|                                                                        |
|     In the year 1878 I took my degree of Doctor of Medicine of the     |
|     University of London, and proceeded to Netley to go through the    |
|     course prescribed for surgeons in the army. Having completed my    |
|     studies there, I was duly attached to the Fifth Northumberland     |
|     Fusiliers as Assistant Surgeon. The regiment was stationed in India|
|     at the time, and before I could join it, the second Afghan war had |
+------------------------------------------------------------------------+
only showing top 20 rows

## **ORC Files**

In [ ]:
# Write and Read OCR

# df.write.orc('filename.orc')
# df = spark.read.orc('filename.orc')

In [ ]:
airport = spark.read.csv("/content/airport-codes.csv", header=True, inferSchema=True)

In [ ]:
airport.show(2)

+-----+-------------+--------------------+------------+---------+-----------+----------+------------+--------+---------+----------+--------------------+
|ident|         type|                name|elevation_ft|continent|iso_country|iso_region|municipality|gps_code|iata_code|local_code|         coordinates|
+-----+-------------+--------------------+------------+---------+-----------+----------+------------+--------+---------+----------+--------------------+
|  00A|     heliport|   Total Rf Heliport|          11|       NA|         US|     US-PA|    Bensalem|     00A|     null|       00A|40.07080078125, -...|
| 00AA|small_airport|Aero B Ranch Airport|        3435|       NA|         US|     US-KS|       Leoti|    00AA|     null|      00AA|38.704022, -101.4...|
+-----+-------------+--------------------+------------+---------+-----------+----------+------------+--------+---------+----------+--------------------+
only showing top 2 rows

In [ ]:
# create orc file

airport.write.orc('airport-codes.orc')

In [ ]:
airport_orc = spark.read.orc('airport-codes.orc')

In [ ]:
airport_orc.show(2)

+-----+-------------+--------------------+------------+---------+-----------+----------+------------+--------+---------+----------+--------------------+
|ident|         type|                name|elevation_ft|continent|iso_country|iso_region|municipality|gps_code|iata_code|local_code|         coordinates|
+-----+-------------+--------------------+------------+---------+-----------+----------+------------+--------+---------+----------+--------------------+
|  00A|     heliport|   Total Rf Heliport|          11|       NA|         US|     US-PA|    Bensalem|     00A|     null|       00A|40.07080078125, -...|
| 00AA|small_airport|Aero B Ranch Airport|        3435|       NA|         US|     US-KS|       Leoti|    00AA|     null|      00AA|38.704022, -101.4...|
+-----+-------------+--------------------+------------+---------+-----------+----------+------------+--------+---------+----------+--------------------+
only showing top 2 rows